### ISSUE TITLE
Tried again with new version, please see results

### ISSUE THREAD

**Issue by Max33M** [NotARobot6969/KextUpdater#2]
Build succeeded.

/Users/alexmyers/KextUpdater/KextUpdater/Program.cs(31,42): warning SYSLIB0014: 'WebRequest.Create(string)' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.' [/Users/alexmyers/KextUpdater/KextUpdater/KextUpdater.csproj]
/Users/alexmyers/KextUpdater/KextUpdater/Program.cs(88,73): warning SYSLIB0014: 'WebRequest.Create(string)' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.' [/Users/alexmyers/KextUpdater/KextUpdater/KextUpdater.csproj]
/Users/alexmyers/KextUpdater/KextUpdater/Program.cs(113,33): warning SYSLIB0014: 'WebClient.WebClient()' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.' [/Users/alexmyers/KextUpdater/KextUpdater/KextUpdater.csproj]
/Users/alexmyers/KextUpdater/KextUpdater/Program.cs(20,18): warning CS8600: Converting null literal or possible null value to non-nullable type. [/Users/alexmyers/KextUpdater/KextUpdater/KextUpdater.csproj]
/Users/alexmyers/KextUpdater/KextUpdater/Program.cs(21,5): warning CS8602: Dereference of a possibly null reference. [/Users/alexmyers/KextUpdater/KextUpdater/KextUpdater.csproj]
/Users/alexmyers/KextUpdater/KextUpdater/Program.cs(39,21): warning CS8600: Converting null literal or possible null value to non-nullable type. [/Users/alexmyers/KextUpdater/KextUpdater/KextUpdater.csproj]
/Users/alexmyers/KextUpdater/KextUpdater/Program.cs(42,24): warning CS8602: Dereference of a possibly null reference. [/Users/alexmyers/KextUpdater/KextUpdater/KextUpdater.csproj]
    7 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.38
alexmyers@MacBook-Air KextUpdater % dotnet run
Please drag and drop your kexts folder onto the console window: /Volumes/SYSTEM/EFI                     
WhateverGreen has been added to the local DB!
Lilu has been added to the local DB!
itlwm has been added to the local DB!
AppleALC has been added to the local DB!
IntelBluetoothFirmware has been added to the local DB!
NVMeFix has been added to the local DB!
AirportItlwm has been added to the local DB!
BlueToolFixup has been added to the local DB!
Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Program.<Main>$(String[] args) in /Users/alexmyers/KextUpdater/KextUpdater/Program.cs:line 54

Did it update my kexts? I'm not sure, it seems that it just added them to the DB.

I did do a fresh clone and then freshly ran the app. Please advise on next steps

**Comment by not-nullptr** [comment]
new pr mightve fixed? feel free to try

**Comment by halal-beef** [comment]
sadly not because the files werent downloading as the temp directory for ur program wasnt there and webclient wouldnt make it, line 54 (now 55) is the issue

**Comment by halal-beef** [comment]
nvm still line 54

**Comment by Max33M** [comment]
Shall I try again?

**Comment by Max33M** [comment]
Didn't mean to close it. Lmk if you'd like me to try again. 
Here's my specs: 
Microsoft Surface Pro 7 1.5ghz quad core intel i7
Intel Iris plus graphics
8gb ram
Mac OS Monterey 12.3.1
I can upload my EFI folder if needed as well. Looking forward to testing it out again. Thanks!

**Comment by halal-beef** [comment]
We'd probably need Ur kexts folder I think that something is being picked up in there and thats what's making it error

**Comment by Max33M** [comment]
Apologies for the delay. I tried to upload a zip of my kexts folder and it was just slightly over the size limit. Here is a Google Drive link to download my kexts folder. Thanks!
https://drive.google.com/file/d/1TbYf-ehFGZFmSYs2UfovayL_aJYjanCs/view?usp=sharing

Also, sorry if it's a bit of a mess. My system works perfectly with what's there, so I just leave it be.

**Comment by halal-beef** [comment]
yeah it seems fine maybe its just the ._filenamehere things but i presume that was cause u zipped ur efi file up in mac os and sent it off, ill try make a dummy oc folder and test ur file

**Comment by halal-beef** [comment]
hmmm when i tried with ur kexts folder it worked perfectly, maybe a one off issue? or just dodgy mac os support

**Comment by halal-beef** [comment]
even with the ._filenamehere

**Comment by not-nullptr** [comment]
probably is, macOS support is iffy as i don't have a mac to test on

**Comment by halal-beef** [comment]
i would debug but ive already deleted my mac os installation

**Comment by halal-beef** [comment]
i think i may have found the issue, ill be updating my fork

**Comment by halal-beef** [comment]
@Max33M https://github.com/halal-beef/KextUpdater/tree/patch-1 try building this

**Comment by Max33M** [comment]
I tried the new fork, wasn't sure if you wanted me to continue the issue here or on the fork. It looks like some of the kexts did indeed update. Pasting the log below.

Please drag and drop your kexts folder onto the console window: /Volumes/SYSTEM/EFI/OC/Kexts                          
WhateverGreen has been added to the local DB!
Lilu has been added to the local DB!
itlwm has been added to the local DB!
AppleALC has been added to the local DB!
IntelBluetoothFirmware has been added to the local DB!
NVMeFix has been added to the local DB!
AirportItlwm has been added to the local DB!
BlueToolFixup has been added to the local DB!
Kext Lilu was updated successfully!
VoodooI2CAtmelMXT was not found in the database. Please create a pull request to add it or an issue with details!
Kext itlwm was updated successfully!
Kext AppleALC was updated successfully!
Kext IntelBluetoothFirmware was updated successfully!
VoodooI2CSynaptics was not found in the database. Please create a pull request to add it or an issue with details!
Kext BlueToolFixup was detected, but was unable to update. Please report which kext this is as a GitHub issue!
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Program.<Main>$(String[] args) in /Users/alexmyers/Desktop/KextUpdater/KextUpdater/Program.cs:line 90
Kext WhateverGreen was updated successfully!
AirportItlwm is not supported by this program because AirportItlwm's file structure is very weird and would require poorly written workarounds to implement.
BrightnessKeys was not found in the database. Please create a pull request to add it or an issue with details!
VoodooI2CHID was not found in the database. Please create a pull request to add it or an issue with details!
VoodooI2CFTE was not found in the database. Please create a pull request to add it or an issue with details!
VoodooI2CELAN was not found in the database. Please create a pull request to add it or an issue with details!
BigSurface was not found in the database. Please create a pull request to add it or an issue with details!
VirtualSMC was not found in the database. Please create a pull request to add it or an issue with details!
USBPorts was not found in the database. Please create a pull request to add it or an issue with details!

**Comment by halal-beef** [comment]
YESSSSSSSSSSSSSSSSSSS

**Comment by halal-beef** [comment]
Bluetoolfixup sadly is broken but everything works tysmmmmmm for testing

**Comment by halal-beef** [comment]
(bluetool fixup needs database update)

**Comment by halal-beef** [comment]
also i removed references to the temp folder as im not sure if it also exists for mac os, i presumed not so i put it in the main program folder but it should be fine

**Comment by not-nullptr** [comment]
database is stored in repo, you can update if you want

**Comment by halal-beef** [comment]
since bluetoolfixup is stored under a huge zip of other kexts do we add it as no support or try to think of a solution

**Comment by Max33M** [comment]
> Bluetoolfixup sadly is broken but everything works tysmmmmmm for testing

Happy to help!
